### ISSUE TITLE
Cordova 3.2.0 org.apache.cordova.api.CordovaPlugin does not exist

### ISSUE THREAD

**Issue by georgik** [phonegap/phonegap-plugin-fast-canvas#11]
I was testing fast-canvas with Cordova 3.2.0. 
There is small compatibility issue in Java code.
It's not possible to compile FastCanvas with Cordova 3.2.0. 
Package org.apache.cordova.api.\* does not not exist.

API was changed and CordovaPlugin is in different package: org.apache.cordova.CordovaPlugin.

It's sufficient to remove .api from imports in FastCanvas.java and FastCanvasMessage.java.

Here is fixed version: https://github.com/georgik/phonegap-plugin-fast-canvas/commit/ae43ea208885d29c7b157712219cd0065077f720

Based on hint: http://stackoverflow.com/questions/17969206/org-apache-cordova-api-doesnt-exist-phonegap-3-0

I'm not sure whether it's feasible to merge this patch to the main project, because it will break compatibility with older code. Maybe it would be good to create branch for older apps.

**Comment by shakiba** [comment]
@georgik Can you please explain how you have got it running with Cordova 3.2, I have not been able to do so, so far.

**Comment by georgik** [comment]
@shakiba This is whole fix: https://github.com/georgik/phonegap-plugin-fast-canvas/commit/ae43ea208885d29c7b157712219cd0065077f720

Try to clone my fork of FastCanvas - https://github.com/georgik/phonegap-plugin-fast-canvas.git

I was trying to use FastCanvas to build simple game.
I also made small research about performance HTML5 Cavas vs FastCanvas: http://georgik.sinusgear.com/2013/12/18/cordova-html5-canvas-vs-fastcanvas-performance/

The performance was not too breathtaking, so I decided to build game just by using HTML5, CSS3, without Canvas. Pefromance was much better then Canvas based app. You can see it here: http://pf2014.sinusgear.com/

**Comment by shakiba** [comment]
@georgik  Thanks! Can you please let me know how you have added it to your Cordova 3.x project?

By the way have you used drawing (other than image pasting) in your benchmark? FastCanvas doesn't support them at all. Maybe it has fell back to default Canvas in your installation. I have experienced major performance improvement with FastCanvas on Android. For benchmark I suggest running FastCanvas example (Hungry Hero) with FastCanvas disabled.

**Comment by georgik** [comment]
@shakiba Thank you for idea how to improve benchmark. You're right I should use more methods for comparing performance. 

Installation:
cordova plugin add https://github.com/georgik/phonegap-plugin-fast-canvas.git

**Comment by shakiba** [comment]
@georgik Thanks, still not working for me! But I'm going to compare it with your game to find out the problem.

**Comment by georgik** [comment]
@shakiba hm, my game is not using FastCanvas, because I use only HTML5 with CSS3 without canvas in the latest version. So it won't help you.

**Comment by shakiba** [comment]
@georgik I just figured it out after having a look at your code! What about benchmark, have you released the source code?

**Comment by georgik** [comment]
@shakiba :-) I mixed two things in the post.

1st. Performance tests have been done on other project. You can check complete archive of project from IntelliJ Idea: http://georgik.sinusgear.com/tmp/html5/easelperformance.zip That was the source for performance comparison.

2nd. Since those results were not too promising I decided to avoid using Canvas. The final application PF2014 is without canvas. 

Sorry for confusion.

**Comment by shakiba** [comment]
@georgik Thanks, I will try it. :)

**Comment by shakiba** [comment]
@georgik  I tried your project, in your benchmark Fast Canvas falls back to HTML Canvas, you can check it by logging value of `FastCanvas.isFast` after calling `FastCanvas.create()`.

**Comment by georgik** [comment]
@shakiba Hm. Then it means that my correction does not work and benchmark displays better performance just because visible canvas had slightly different size.

I'll remove article about performance from my blog since measured data are invalid.
Since this correction is invalid, I'm closing this issue.

Thank you for pointing out that mistake.

**Comment by shakiba** [comment]
NP, but I think this issue is still valid, it seems these changes are required to use FastCanvas with Cordova 3.x but probably not enough, I'm going to spend some more time to figure it out.

**Comment by shakiba** [comment]
I have successfully
- created a Cordova 3.3.1 project using `cordova create ...; cordova platform add android`
- manually added FastCanvas plugin files and applied this fix
- added www files from example game

and tested the game on an Android device with FastCanvas enabled.
