### ISSUE TITLE
Is there any plan to extend Canvas API support?

### ISSUE THREAD

**Issue by shakiba** [phonegap/phonegap-plugin-fast-canvas#2]
Just found this project, looks very interesting, but Canvas API support seems very limited. Is there any plan to extend it, specially supporting arc/rect fill/stroke drawing methods?

**Comment by jmott** [comment]
No, those methods in particular are not friendly to the GPU. Leaving them out is what allowed fast canvas to be accelerated.

**Comment by shakiba** [comment]
I see, is there anything beyond drawImage going to be added in future?

**Comment by jmott** [comment]
There are no plans to do so - fast canvas works because of its narrow focus, for those apps (like 2d games using sprite sheets) that need just those features.

**Comment by shakiba** [comment]
Thanks! I guess I should try harder to think in image/transform-only! :)

**Comment by degenet** [comment]
Is there any way to incorporate the context.getImageData and putImageData methods?
