### ISSUE TITLE
Incorrect Repository Name

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-plugin-fast-canvas#3]
With the [Apache Cordova](http://cordova.io) community, we have decided on the following naming conventions:

**Platforms**: cordova-name
**Plugins**: cordova-plugin-name
**Applications**: cordova-app-name

Since PhoneGap is a distribution of Apache Cordova, it should make every effort to respect and match existing conventions.

**Platforms**: phonegap-name
**Plugins**: phonegap-plugin-name
**Applications**: phonegap-app-name

So, `phonegap-fast-canvas-plugin` should be renamed to: `phonegap-plugin-fast-canvas`. It is better to do this now, before there is strong adoption (a mistake the `phonegap-facebook-plugin` made).

**Comment by jmott** [comment]
Fixed

**Comment by mwbrooks** [comment]
Thanks dude!
