### ISSUE TITLE
Object.defineProperty() is not supported on older android devices.

### ISSUE THREAD

**Issue by shakiba** [phonegap/phonegap-plugin-fast-canvas#5]
Object.defineProperty is used in FastCanvas.js but it is not supported on older android devices, I guess android<4, but I'm sure it doesn't work on api 10.

See: http://bugs.jquery.com/ticket/13494

**Comment by shakiba** [comment]
Exact error is:
TypeError: defineProperty is not supported on DOM Objects at file:///android_asset/www/FastCanvas.js:580

**Comment by jmott** [comment]
Fixed
