### ISSUE TITLE
How can I add a banner above the canvas-like surface?

### ISSUE THREAD

**Issue by sgmonda** [phonegap/phonegap-plugin-fast-canvas#6]
I've tried to add a `<div>` element with a very high `z-index` style property, and it is shown right when game is rendered with an HTML canvas (for example in my desktop browser). But when running on Android, as fast-canvas covers everything, It is not possible to see that div.

How can I add a banner above the fast-canvas surface?

**Comment by jmott** [comment]
You can’t.  With FastCanvas, all content must be drawn on the canvas – no HTML. This kind of limitation, irritating as it may be, is what allows it to be fast.

**Comment by sgmonda** [comment]
I've also tried to integrate the AdMob SDK, modifying the main layout (Java code). Now fast-canvas height is reduced, creating a free space for the ad, but ad is not shown. If I turn off fast-canvas, then the ad is shown without problems, next to the HTML5 canvas.

Please, I need to add an ad while fast-canvas is visible. I can't be the only one who needs it! :-(
It must be possible.

**Comment by jmott** [comment]
The only thing I can think of is rendering your banners to textures and then displaying them yourself using fast canvas. There is no getting around the requirement that fast canvas be full screen.

**Comment by shakiba** [comment]
Is it possible to render it inside another View (another WebView) over FastCanvas?  According to following Q/A it seems possible to render another View over OpenGL SurfaceView or I have missed something here!
http://stackoverflow.com/questions/2899139/opengl-and-layouts

**Comment by jmott** [comment]
Sounds cool - give it a try, let us know how it works out.

**Comment by shakiba** [comment]
I will try it! :)
