### ISSUE TITLE
App crash when giving it the focus after going home

### ISSUE THREAD

**Issue by sgmonda** [phonegap/phonegap-plugin-fast-canvas#8]
I've an important problem and I need to know if anybody else has experimented it: when I put my opened fast-canvas app in the background (pressing home button), if I give it the focus again it crashes. I can't see anything strange in logcat (or I don't find it).
Any idea?
Thank you

**Comment by jmott** [comment]
Do you see the same behavior with phonegap-app-fast-canvas - Hungry Hero? If not please compare your app logic to its app logic, particularly in regards to releasing and reloading textures during a suspend.

**Comment by sgmonda** [comment]
I've tried with Hungry Hero and I experiment the same issue. Could you check if it happens to you too?

**Comment by northwind** [comment]
I also found this problem on my Galaxy Nexus device

**Comment by shakiba** [comment]
It seems that this is not an unknown issue with GLSurfaceView (search for 'surfaceDestroyed crash') but I wasn't able to find a solution in FastCanvas case, just a dirty workaround is to call finish() inside onPause().

**Comment by shakiba** [comment]
A better workaround is to add two main lines of DriodGap activity onDestroy to FastCanvasView surfaceDestroyed.

**Comment by jmott** [comment]
Care to send us a pull request with your fix?

**Comment by jmott** [comment]
Patch merged - thanks!

**Comment by shakiba** [comment]
Thanks, however here are my findings, maybe they help to find a better fix, I'm not sure mine is good enough:

I have investigated 3 cases:

Open-back-open: OK.
On back button surface is destroyed and activity is destroyed which kills the app completely. On second open app/activity is opened normally.

Open-lock-open: OK.
On locking screen, surface is not destroyed and activity is not destroyed. On unlocking everything is still working.

Open-home-open: Crash.
On home button surface is destroyed but activity is not destroyed. On second open FastCanvas is started again while it has not been killed completely, so it crashes.
There are two workarounds, one is to kill app on surfaceDestroy (my pull request) it works like open-back-open, the second is @sgmonda suggestion which is commenting out surfaceDestroy it works like open-lock-open.
